dependencies:
  - numpy
  - scipy
  - matplotlib
  - setuptools
  - pybind11
  - healpy
  - nbsphinx
  - starry
  - pip:
    - Pillow
    - batman-package
    - tqdm
    - emcee
    - corner
    - wget
    - pandas
    - lightkurve


